-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library aluProc_lib;
use aluProc_lib.types.all;


entity \add4FSVecProc\ is
     port (\a\ : in fsvec_4_std_logic;
           \b\ : in fsvec_4_std_logic;
           \cout\ : out std_logic;
           \sum\ : out fsvec_4_std_logic);
end entity \add4FSVecProc\;


architecture synthesizable of \add4FSVecProc\ is
     signal \Zero_out1\ : std_logic;
     signal \split_a_out1\ : std_logic;
     signal \split_a_out2\ : std_logic;
     signal \split_a_out3\ : std_logic;
     signal \split_a_out4\ : std_logic;
     signal \split_b_out1\ : std_logic;
     signal \split_b_out2\ : std_logic;
     signal \split_b_out3\ : std_logic;
     signal \split_b_out4\ : std_logic;
     signal \adder_out1\ : std_logic;
     signal \adder_out2\ : std_logic;
     signal \adder_out3\ : std_logic;
     signal \adder_out4\ : std_logic;
     signal \adder_out5\ : std_logic;
     signal \merge_out1\ : fsvec_4_std_logic;
begin
     \Zero\ : entity work.\zeroProc\
                   port map (\zero\ => \Zero_out1\);
     
     \split_a\ : entity work.\convFromFSVec4Proc\
                      port map (\vector4\ => \a\,
                                \v3\ => \split_a_out1\,
                                \v2\ => \split_a_out2\,
                                \v1\ => \split_a_out3\,
                                \v0\ => \split_a_out4\);
     
     \split_b\ : entity work.\convFromFSVec4Proc\
                      port map (\vector4\ => \b\,
                                \v3\ => \split_b_out1\,
                                \v2\ => \split_b_out2\,
                                \v1\ => \split_b_out3\,
                                \v0\ => \split_b_out4\);
     
     \adder\ : entity work.\fourBitAdder\
                    port map (\C_IN\ => \Zero_out1\,
                              \A3\ => \split_a_out1\,
                              \A2\ => \split_a_out2\,
                              \A1\ => \split_a_out3\,
                              \A0\ => \split_a_out4\,
                              \B3\ => \split_b_out1\,
                              \B2\ => \split_b_out2\,
                              \B1\ => \split_b_out3\,
                              \B0\ => \split_b_out4\,
                              \C_OUT\ => \adder_out1\,
                              \SUM3\ => \adder_out2\,
                              \SUM2\ => \adder_out3\,
                              \SUM1\ => \adder_out4\,
                              \SUM0\ => \adder_out5\);
     
     \merge\ : entity work.\convToFSVec4Proc\
                    port map (\x3\ => \adder_out2\,
                              \x2\ => \adder_out3\,
                              \x1\ => \adder_out4\,
                              \x0\ => \adder_out5\,
                              \vec4\ => \merge_out1\);
     
     \cout\ <= \adder_out1\;
     
     \sum\ <= \merge_out1\;
end architecture synthesizable;
