-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library aluProc_lib;
use aluProc_lib.types.all;


entity \lslProc\ is
     port (\in\ : in fsvec_4_std_logic;
           \out\ : out fsvec_4_std_logic);
end entity \lslProc\;


architecture synthesizable of \lslProc\ is
     signal \lsl_out\ : fsvec_4_std_logic;
begin
     \lsl\ : block
          port (\lsl_in1\ : in fsvec_4_std_logic;
                \lsl_out\ : out fsvec_4_std_logic);
          port map (\lsl_in1\ => \in\,
                    \lsl_out\ => \lsl_out\);
          function \lslFun\ (\a\ : fsvec_4_std_logic)
                            return fsvec_4_std_logic is
          begin
               return shiftl(\a\, '0');
          end;
     begin
          \lsl_out\ <= \lslFun\(\a\ => \in\);
     end block \lsl\;
     
     \out\ <= \lsl_out\;
end architecture synthesizable;
