-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library aluProc_lib;
use aluProc_lib.types.all;


entity \zeroProc\ is
     port (\zero\ : out std_logic);
end entity \zeroProc\;


architecture synthesizable of \zeroProc\ is
     signal \low_out\ : std_logic := '0';
begin
     \zero\ <= \low_out\;
end architecture synthesizable;
