-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;


package types is

     type fsvec_std_logic is array (fsvec_index range <>) of std_logic;
     
     type tup_4_std_logic_std_logic_std_logic_std_logic is
          record tup_1 : std_logic;
                 tup_2 : std_logic;
                 tup_3 : std_logic;
                 tup_4 : std_logic;
          end record;
     
     type tup_2_std_logic_std_logic is
          record tup_1 : std_logic;
                 tup_2 : std_logic;
          end record;
     
     subtype fsvec_4_std_logic is fsvec_std_logic (0 to 3);
     
     subtype fsvec_2_std_logic is fsvec_std_logic (0 to 1);
     
     function ex (vec : fsvec_std_logic;
                  ix : natural)
                 return std_logic;
     
     function sel (f : natural;
                   n : natural;
                   s : natural;
                   vec : fsvec_std_logic)
                  return fsvec_std_logic;
     
     function empty return fsvec_std_logic;
     
     function length (vec : fsvec_std_logic)
                     return natural;
     
     function isnull (vec : fsvec_std_logic)
                     return boolean;
     
     function replace (vec : fsvec_std_logic;
                       i : natural;
                       a : std_logic)
                      return fsvec_std_logic;
     
     function head (vec : fsvec_std_logic)
                   return std_logic;
     
     function last (vec : fsvec_std_logic)
                   return std_logic;
     
     function init (vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function tail (vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function take (n : natural;
                    vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function drop (n : natural;
                    vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function shiftl (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic;
     
     function shiftr (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic;
     
     function rotl (vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function rotr (vec : fsvec_std_logic)
                   return fsvec_std_logic;
     
     function reverse (vec : fsvec_std_logic)
                      return fsvec_std_logic;
     
     function copy (n : natural;
                    a : std_logic)
                   return fsvec_std_logic;
     
     function plusgt (a : std_logic;
                      vec : fsvec_std_logic)
                     return fsvec_std_logic;
     
     function ltplus (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic;
     
     function plusplus (vec1 : fsvec_std_logic;
                        vec2 : fsvec_std_logic)
                       return fsvec_std_logic;
     
     function singleton (a : std_logic)
                        return fsvec_std_logic;
     
     function show (vec : fsvec_std_logic)
                   return string;
     
     function default return fsvec_std_logic;
     
     function default return tup_4_std_logic_std_logic_std_logic_std_logic;
     
     function show (tup : tup_4_std_logic_std_logic_std_logic_std_logic)
                   return string;
     
     function default return tup_2_std_logic_std_logic;
     
     function show (tup : tup_2_std_logic_std_logic)
                   return string;

end package types;


package body types is

     function ex (vec : fsvec_std_logic;
                  ix : natural)
                 return std_logic is
     begin
          return vec(ix);
     end;
     
     function sel (f : natural;
                   n : natural;
                   s : natural;
                   vec : fsvec_std_logic)
                  return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to n - 1);
     begin
          for i in res'range loop
               res(i) := vec(f + i * s);
          end loop;
          return res;
     end;
     
     function empty return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to -1);
     begin
          return res;
     end;
     
     function length (vec : fsvec_std_logic)
                     return natural is
     begin
          return vec'length;
     end;
     
     function isnull (vec : fsvec_std_logic)
                     return boolean is
     begin
          return vec'length = 0;
     end;
     
     function replace (vec : fsvec_std_logic;
                       i : natural;
                       a : std_logic)
                      return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          res := vec(0 to i - 1) & a & vec(i + 1 to vec'length - 1);
          return res;
     end;
     
     function head (vec : fsvec_std_logic)
                   return std_logic is
     begin
          return vec(0);
     end;
     
     function last (vec : fsvec_std_logic)
                   return std_logic is
     begin
          return vec(vec'length - 1);
     end;
     
     function init (vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 2);
     begin
          res := vec(0 to vec'length - 2);
          return res;
     end;
     
     function tail (vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 2);
     begin
          res := vec(1 to vec'length - 1);
          return res;
     end;
     
     function take (n : natural;
                    vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to n - 1);
     begin
          res := vec(1 to n - 1);
          return res;
     end;
     
     function drop (n : natural;
                    vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - n - 1);
     begin
          res := vec(n to vec'length - 1);
          return res;
     end;
     
     function shiftl (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          res := a & init(vec);
          return res;
     end;
     
     function shiftr (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          res := tail(vec) & a;
          return res;
     end;
     
     function rotl (vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          if isnull(vec) then
               res := vec;
          else
               res := last(vec) & init(vec);
          end if;
          return res;
     end;
     
     function rotr (vec : fsvec_std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          if isnull(vec) then
               res := vec;
          else
               res := last(vec) & init(vec);
          end if;
          return res;
     end;
     
     function reverse (vec : fsvec_std_logic)
                      return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length - 1);
     begin
          for i in res'range loop
               res(vec'length - i - 1) := vec(i);
          end loop;
          return res;
     end;
     
     function copy (n : natural;
                    a : std_logic)
                   return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to n - 1) := (others => a);
     begin
          return res;
     end;
     
     function plusgt (a : std_logic;
                      vec : fsvec_std_logic)
                     return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length);
     begin
          res := a & vec;
          return res;
     end;
     
     function ltplus (vec : fsvec_std_logic;
                      a : std_logic)
                     return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec'length);
     begin
          res := vec & a;
          return res;
     end;
     
     function plusplus (vec1 : fsvec_std_logic;
                        vec2 : fsvec_std_logic)
                       return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to vec1'length + vec2'length - 1);
     begin
          res := vec1 & vec2;
          return res;
     end;
     
     function singleton (a : std_logic)
                        return fsvec_std_logic is
          variable res : fsvec_std_logic (0 to 0) := (others => a);
     begin
          return res;
     end;
     
     function show (vec : fsvec_std_logic)
                   return string is
          function doshow (vec : fsvec_std_logic)
                          return string is
          begin
               case vec'length is
                    when 0 =>
                         return "";
                    when 1 =>
                         return show(head(vec));
                    when others =>
                         return show(head(vec)) & ',' & doshow(tail(vec));
               end case;
          end;
     begin
          return '<' & doshow(vec) & '>';
     end;
     
     function default return fsvec_std_logic is
     begin
          return empty;
     end;
     
     function default return tup_4_std_logic_std_logic_std_logic_std_logic is
     begin
          return (default, default, default, default);
     end;
     
     function show (tup : tup_4_std_logic_std_logic_std_logic_std_logic)
                   return string is
     begin
          return '(' &
                 (show(tup.tup_1) & ',' &
                  (show(tup.tup_2) & ',' &
                   (show(tup.tup_3) & ',' & show(tup.tup_4)))) &
                 ')';
     end;
     
     function default return tup_2_std_logic_std_logic is
     begin
          return (default, default);
     end;
     
     function show (tup : tup_2_std_logic_std_logic)
                   return string is
     begin
          return '(' & (show(tup.tup_1) & ',' & show(tup.tup_2)) & ')';
     end;

end package body types;
